import { InventoryBase } from "./InventoryBase.js";

export interface InventorySettings extends InventoryBase {
  negativeStockAllowed: boolean;
  defaultCostingMethod: "AVERAGE" | "FIFO" | "STANDARD";
  defaultWarehouseId?: string;
  defaultUnitId?: string;
  requireLocation: boolean;
  requireLot: boolean;
  requireSerial: boolean;
  allowBackdatedDocuments: boolean;
  autoPostReceipts: boolean;
  autoPostIssues: boolean;
  autoGenerateDocumentNumbers: boolean;
  documentNumberPrefix: string;
  decimalQuantityPlaces: number;
  decimalCostPlaces: number;
}
