import { registerAppIPC } from "./ipc/shared/app.ipc.js";
import { registerIncidentIPC } from "./ipc/shared/incidents.ipc.js";
import { registerAttendanceIPC } from "./ipc/modules/hr/attendances.ipc.js";
import { registerAdminUsersIPC } from "./ipc/shared/admin_users.ipc.js";
import { registerAttendanceReportIPC } from "./ipc/modules/hr/attendance_report.ipc.js";
import { registerAuthIPC } from "./ipc/shared/auth.ipc.js";
import { registerEmployeeIPC } from "./ipc/modules/hr/employees.ipc.js";
import { registerEmployeeDocumentIPC } from "./ipc/modules/hr/employees_documents.ipc.js";
import { registerLeaveIPC } from "./ipc/modules/hr/leaves.ipc.js";
import { registerNotificationIPC } from "./ipc/shared/notification.ipc.js";
import { registerOfflineUsersIPC } from "./ipc/shared/offline_users.ipc.js";
import { registerPayrollEmployeeProfileIPC } from "./ipc/modules/hr/payrollEmployeeProfile.ipc.js";
import { registerPayrollComponentIPC } from "./ipc/modules/hr/payroll_components.ipc.js";
import { registerPayrollGenerationIPC } from "./ipc/modules/hr/payroll_run.ipc.js";
import { registerSyncIPC } from "./ipc/shared/sync.ipc.js";
import { registerTaskIPC } from "./ipc/shared/tasks.ipc.js";
import { registerTaskCommentIPC } from "./ipc/shared/tasks_comments.ipc.js";
import { registerPayrollSettingsIPC } from "./ipc/modules/hr/payroll_settings.ipc.js";
import { registerAttendanceDailyCheckIPC } from "./ipc/modules/hr/attendance_daily_check.ipc.js";
import { registerEmailIPC } from "./ipc/shared/email.ipc.js";
import { registerTransportAllowanceIpc } from "./ipc/modules/hr/transportAllowance.ipc.js";
import { registerCompanyIpc } from "./ipc/shared/companies.ipc.js";

export function registerIPCHandlers() {
  registerAuthIPC();
  registerOfflineUsersIPC();
  registerEmployeeIPC();
  registerEmployeeDocumentIPC();
  registerAttendanceIPC();
  registerAttendanceDailyCheckIPC();
  registerAttendanceReportIPC();
  registerLeaveIPC();
  registerTaskIPC();
  registerIncidentIPC();
  registerTaskCommentIPC();
  registerAdminUsersIPC();
  registerSyncIPC();
  registerAppIPC();
  registerPayrollSettingsIPC();
  registerPayrollComponentIPC();
  registerPayrollEmployeeProfileIPC();
  registerPayrollGenerationIPC();
  registerNotificationIPC();
  registerEmailIPC();
  registerTransportAllowanceIpc();
  registerCompanyIpc();
}
